### ISSUE TITLE
I can't find the data

### ISSUE THREAD

**Issue by Ebimsv** [ThomasDarby/DataScience#1]
Hello
Thank you for your good code

in "COVID-19 And K-Means Clustering" file 
Where can I download this data ??

{"stateCentersOfPopulation2010.csv" 
"stateArea.csv"}

@ThomasDarby

**Comment by ThomasDarby** [comment]
My apologies, I'd forgotten to upload them! You can find these files (and all future supporting data) under the "data" directory at the project root.
